#!/system/bin/sh

# Shared helpers for the EasyTier Magisk/KernelSU/APatch module.
# Keep this file POSIX sh compatible: Android /system/bin/sh is mksh.

MODDIR=${MODDIR:-${0%/*}}
CONFIG_DIR="${MODDIR}/config"
CONFIG_FILE="${CONFIG_DIR}/config.toml"
COMMAND_ARGS="${CONFIG_DIR}/command_args"
LOG_FILE="${MODDIR}/log.log"
MODULE_PROP="${MODDIR}/module.prop"
EASYTIER_CORE="${MODDIR}/easytier-core"
EASYTIER_CLI="${MODDIR}/easytier-cli"
EASYTIER_WEB="${MODDIR}/easytier-web"
MODULE_DISABLE_FILE="${MODDIR}/disable"
CORE_DISABLE_FILE="${MODDIR}/disable_core"
WEB_DISABLE_FILE="${MODDIR}/disable_web"
START_ON_BOOT_FILE="${MODDIR}/start_on_boot"
IP_RULE_ENABLE_FILE="${MODDIR}/enable_IP_rule"
DEFAULT_WEB_PORT="11211"
DEFAULT_CONFIG_SERVER_PORT="22020"
DEFAULT_CONFIG_SERVER_PROTOCOL="udp"
UPDATE_LOCK="${MODDIR}/update.lock"
CONTROL_LOCK_DIR="${MODDIR}/run/lock"
RUN_DIR="${MODDIR}/run"
CORE_PID_FILE="${RUN_DIR}/easytier-core.pid"
WEB_PID_FILE="${RUN_DIR}/easytier-web.pid"

mkdir -p "${CONFIG_DIR}" "${RUN_DIR}" 2>/dev/null

now() {
    date "+%Y-%m-%d %H:%M:%S"
}

log_msg() {
    echo "[$(now)] $*" >> "${LOG_FILE}"
}

json_escape() {
    # Good enough for status/log JSON values generated by shell scripts.
    sed 's/\\/\\\\/g; s/"/\\"/g; s/\r/\\r/g; s/\t/\\t/g' | awk '{printf "%s%s", sep, $0; sep="\\n"}'
}

update_module_description() {
    status_message="$1"
    [ -f "${MODULE_PROP}" ] || return 0
    new_desc="description=[状态] ${status_message}"
    if grep -q '^description=' "${MODULE_PROP}" 2>/dev/null; then
        current_desc=$(grep '^description=' "${MODULE_PROP}" | head -n 1)
        [ "${current_desc}" = "${new_desc}" ] && return 0
        sed -i "s#^description=.*#${new_desc}#" "${MODULE_PROP}"
    else
        echo "${new_desc}" >> "${MODULE_PROP}"
    fi
}

get_device_hostname() {
    brand=$(getprop ro.product.brand 2>/dev/null | tr ' ' '-')
    model=$(getprop ro.product.model 2>/dev/null | tr ' ' '-')
    [ -n "${brand}${model}" ] || { echo "android"; return; }
    echo "${brand}-${model}" | sed 's/^-//; s/-$//'
}

ensure_tun() {
    if [ ! -e /dev/net/tun ]; then
        [ -d /dev/net ] || mkdir -p /dev/net 2>/dev/null
        [ -e /dev/tun ] && ln -s /dev/tun /dev/net/tun 2>/dev/null
    fi
}

is_core_running() {
    pgrep -f "${MODDIR}/easytier-core" >/dev/null 2>&1
}

is_web_running() {
    pgrep -f "${MODDIR}/easytier-web" >/dev/null 2>&1
}

kill_core() {
    pkill -f "${MODDIR}/easytier-core" >/dev/null 2>&1 || true
    rm -f "${CORE_PID_FILE}" 2>/dev/null
}

kill_web() {
    pkill -f "${MODDIR}/easytier-web" >/dev/null 2>&1 || true
    rm -f "${WEB_PID_FILE}" 2>/dev/null
}

get_web_port() {
    if [ -f "${CONFIG_DIR}/web_port" ]; then
        port=$(tr -dc '0-9' < "${CONFIG_DIR}/web_port" | head -c 5)
        [ -n "${port}" ] && { echo "${port}"; return; }
    fi
    echo "${DEFAULT_WEB_PORT}"
}

get_config_server_port() {
    if [ -f "${CONFIG_DIR}/config_server_port" ]; then
        port=$(tr -dc '0-9' < "${CONFIG_DIR}/config_server_port" | head -c 5)
        [ -n "${port}" ] && { echo "${port}"; return; }
    fi
    echo "${DEFAULT_CONFIG_SERVER_PORT}"
}

get_config_server_protocol() {
    if [ -f "${CONFIG_DIR}/config_server_protocol" ]; then
        proto=$(tr -cd '[:alnum:]_-' < "${CONFIG_DIR}/config_server_protocol" | head -c 16)
        [ -n "${proto}" ] && { echo "${proto}"; return; }
    fi
    echo "${DEFAULT_CONFIG_SERVER_PROTOCOL}"
}

core_mode() {
    if [ -f "${COMMAND_ARGS}" ]; then
        echo "启动参数模式"
    else
        echo "配置文件模式"
    fi
}

start_core_once() {
    ensure_tun
    if [ -f "${CORE_DISABLE_FILE}" ]; then
        log_msg "core start skipped: disabled"
        return 2
    fi
    if is_core_running; then
        log_msg "core already running"
        return 0
    fi
    if [ ! -x "${EASYTIER_CORE}" ]; then
        log_msg "core binary missing or not executable: ${EASYTIER_CORE}"
        update_module_description "主程序缺少二进制文件"
        return 1
    fi
    if [ ! -f "${CONFIG_FILE}" ] && [ ! -f "${COMMAND_ARGS}" ]; then
        log_msg "core start failed: missing config.toml or command_args"
        update_module_description "缺少配置文件或启动参数文件"
        return 1
    fi

    device_hostname=$(get_device_hostname)
    if [ -f "${COMMAND_ARGS}" ]; then
        # command_args mode intentionally uses shell word splitting, matching the upstream module behavior.
        cmd_content=$(tr '\r\n' ' ' < "${COMMAND_ARGS}")
        if echo "${cmd_content}" | grep -q -- "--hostname"; then
            final_args="${cmd_content}"
        else
            final_args="${cmd_content} --hostname ${device_hostname}"
        fi
        log_msg "starting easytier-core with command_args"
        # shellcheck disable=SC2086
        TZ=Asia/Shanghai "${EASYTIER_CORE}" ${final_args} > "${LOG_FILE}" 2>&1 &
    else
        log_msg "starting easytier-core with config.toml"
        if grep -q "^[[:space:]]*hostname[[:space:]]*=" "${CONFIG_FILE}" 2>/dev/null; then
            TZ=Asia/Shanghai "${EASYTIER_CORE}" -c "${CONFIG_FILE}" > "${LOG_FILE}" 2>&1 &
        else
            TZ=Asia/Shanghai "${EASYTIER_CORE}" -c "${CONFIG_FILE}" --hostname "${device_hostname}" > "${LOG_FILE}" 2>&1 &
        fi
    fi
    echo "$!" > "${CORE_PID_FILE}"
    sleep 2
    if is_core_running; then
        if ! ip rule show 2>/dev/null | grep -qE '^[0-9]+:[[:space:]]+from all lookup main$'; then
            ip rule add from all lookup main >/dev/null 2>&1 || true
        fi
        update_module_description "主程序正在运行（$(core_mode)）| $(redir_status)"
        return 0
    fi
    update_module_description "主程序启动失败，请检查配置文件或启动参数"
    return 1
}

start_web_once() {
    if [ -f "${WEB_DISABLE_FILE}" ]; then
        log_msg "web start skipped: disabled"
        return 2
    fi
    if is_web_running; then
        log_msg "web already running"
        return 0
    fi
    if [ ! -x "${EASYTIER_WEB}" ]; then
        log_msg "web binary missing or not executable: ${EASYTIER_WEB}"
        return 1
    fi
    web_port=$(get_web_port)
    cfg_port=$(get_config_server_port)
    cfg_proto=$(get_config_server_protocol)
    mkdir -p "${CONFIG_DIR}/web" 2>/dev/null
    log_msg "starting easytier-web on 0.0.0.0:${web_port}; config server ${cfg_proto}:${cfg_port}"
    TZ=Asia/Shanghai "${EASYTIER_WEB}" \
        --db "${CONFIG_DIR}/web/et.db" \
        --config-server-port "${cfg_port}" \
        --config-server-protocol "${cfg_proto}" \
        --api-server-addr 0.0.0.0 \
        --api-server-port "${web_port}" \
        --web-server-addr 0.0.0.0 \
        --file-log-dir "${CONFIG_DIR}/web/logs" \
        --disable-registration false \
        > "${MODDIR}/web.log" 2>&1 &
    echo "$!" > "${WEB_PID_FILE}"
    sleep 2
    is_web_running
}

redir_status() {
    if [ -f "${IP_RULE_ENABLE_FILE}" ]; then
        echo "转发已激活"
    else
        echo "转发已禁用"
    fi
}

module_status_json() {
    if is_core_running; then core_running=true; else core_running=false; fi
    if is_web_running; then web_running=true; else web_running=false; fi
    if [ -f "${MODULE_DISABLE_FILE}" ]; then module_enabled=false; else module_enabled=true; fi
    if [ -f "${CORE_DISABLE_FILE}" ]; then core_enabled=false; else core_enabled=true; fi
    if [ -f "${WEB_DISABLE_FILE}" ]; then web_enabled=false; else web_enabled=true; fi
    if [ -f "${START_ON_BOOT_FILE}" ]; then start_on_boot=true; else start_on_boot=false; fi
    if [ -f "${IP_RULE_ENABLE_FILE}" ]; then ip_rule_enabled=true; else ip_rule_enabled=false; fi
    core_version=""
    web_version=""
    if [ -x "${EASYTIER_CORE}" ]; then core_version=$("${EASYTIER_CORE}" --version 2>/dev/null | head -n 1); fi
    if [ -x "${EASYTIER_WEB}" ]; then web_version=$("${EASYTIER_WEB}" --version 2>/dev/null | head -n 1); fi
    module_version=$(grep '^version=' "${MODULE_PROP}" 2>/dev/null | head -n 1 | cut -d= -f2-)
    printf '{'
    printf '"module_enabled":%s,' "${module_enabled}"
    printf '"core_running":%s,' "${core_running}"
    printf '"web_running":%s,' "${web_running}"
    printf '"core_enabled":%s,' "${core_enabled}"
    printf '"web_enabled":%s,' "${web_enabled}"
    printf '"start_on_boot":%s,' "${start_on_boot}"
    printf '"ip_rule_enabled":%s,' "${ip_rule_enabled}"
    printf '"web_url":"http://127.0.0.1:%s/",' "$(get_web_port)"
    printf '"config_path":"%s",' "${CONFIG_FILE}"
    printf '"command_args_path":"%s",' "${COMMAND_ARGS}"
    printf '"module_version":"%s",' "$(printf '%s' "${module_version}" | json_escape)"
    printf '"core_version":"%s",' "$(printf '%s' "${core_version}" | json_escape)"
    printf '"web_version":"%s"' "$(printf '%s' "${web_version}" | json_escape)"
    printf '}\n'
}

control_lock_acquire() {
    mkdir -p "${RUN_DIR}" 2>/dev/null
    i=0
    while ! mkdir "${CONTROL_LOCK_DIR}" 2>/dev/null; do
        i=$((i + 1))
        [ "$i" -gt 50 ] && return 1
        sleep 0.1
    done
    return 0
}

control_lock_release() {
    rmdir "${CONTROL_LOCK_DIR}" 2>/dev/null || true
}
