#!/system/bin/sh

# Shared helpers for the EasyTier Magisk/KernelSU/APatch module.
# Keep this file POSIX sh compatible: Android /system/bin/sh is mksh.

MODDIR=${MODDIR:-${0%/*}}
CONFIG_DIR="${MODDIR}/config"
CONFIG_FILE="${CONFIG_DIR}/config.toml"
COMMAND_ARGS="${CONFIG_DIR}/command_args"
LOG_FILE="${MODDIR}/log.log"
MODULE_PROP="${MODDIR}/module.prop"
EASYTIER_CORE="${MODDIR}/easytier-core"
EASYTIER_CLI="${MODDIR}/easytier-cli"
MODULE_DISABLE_FILE="${MODDIR}/disable"
CORE_DISABLE_FILE="${MODDIR}/disable_core"
START_ON_BOOT_FILE="${MODDIR}/start_on_boot"
IP_RULE_ENABLE_FILE="${MODDIR}/enable_IP_rule"
CONTROL_LOCK_DIR="${MODDIR}/run/lock"
CONTROL_LOCK_OWNER_DIR=""
CONTROL_LOCK_OWNER_START=""
RUN_DIR="${MODDIR}/run"
CORE_PID_FILE="${RUN_DIR}/easytier-core.pid"

mkdir -p "${CONFIG_DIR}" "${RUN_DIR}" 2>/dev/null

now() {
    date "+%Y-%m-%d %H:%M:%S"
}

log_msg() {
    echo "[$(now)] $*" >> "${LOG_FILE}"
}

json_escape() {
    # Good enough for status/log JSON values generated by shell scripts.
    sed 's/\\/\\\\/g; s/"/\\"/g; s/\r/\\r/g; s/\t/\\t/g' | awk '{printf "%s%s", sep, $0; sep="\\n"}'
}

update_module_description() {
    status_message="$1"
    [ -f "${MODULE_PROP}" ] || return 0
    new_desc="description=[状态] ${status_message}"
    if grep -q '^description=' "${MODULE_PROP}" 2>/dev/null; then
        current_desc=$(grep '^description=' "${MODULE_PROP}" | head -n 1)
        [ "${current_desc}" = "${new_desc}" ] && return 0
        sed -i "s#^description=.*#${new_desc}#" "${MODULE_PROP}"
    else
        echo "${new_desc}" >> "${MODULE_PROP}"
    fi
}

get_device_hostname() {
    brand=$(getprop ro.product.brand 2>/dev/null | tr ' ' '-')
    model=$(getprop ro.product.model 2>/dev/null | tr ' ' '-')
    [ -n "${brand}${model}" ] || { echo "android"; return; }
    echo "${brand}-${model}" | sed 's/^-//; s/-$//'
}

ensure_tun() {
    if [ ! -e /dev/net/tun ]; then
        [ -d /dev/net ] || mkdir -p /dev/net 2>/dev/null
        [ -e /dev/tun ] && ln -s /dev/tun /dev/net/tun 2>/dev/null
    fi
}

core_process_start_time() {
    process_pid="$1"
    process_executable=$(readlink "/proc/${process_pid}/exe" 2>/dev/null) || return 1
    case "${process_executable}" in
        "${EASYTIER_CORE}"|"${EASYTIER_CORE} (deleted)") ;;
        *) return 1 ;;
    esac
    process_stat_line=""
    IFS= read -r process_stat_line < "/proc/${process_pid}/stat" || return 1
    process_stat_fields=${process_stat_line##*) }
    set -- ${process_stat_fields}
    [ "$#" -ge 20 ] || return 1
    case "$1" in Z|X) return 1 ;; esac
    shift 19
    echo "$1"
}

core_process_records() {
    CORE_PROCESS_RECORDS=""
    CORE_PROCESS_COUNT=0
    CORE_PROCESS_DISCOVERY_ERROR=0
    if ! command -v pgrep >/dev/null 2>&1; then
        CORE_PROCESS_DISCOVERY_ERROR=1
        return 1
    fi

    candidate_pids=$(pgrep -f 'easytier-core' 2>/dev/null)
    search_status=$?
    if [ "${search_status}" -gt 1 ]; then
        CORE_PROCESS_DISCOVERY_ERROR=1
        return 1
    fi
    for candidate_pid in ${candidate_pids}; do
        candidate_start_time=$(core_process_start_time "${candidate_pid}") || continue
        CORE_PROCESS_RECORDS="${CORE_PROCESS_RECORDS}${candidate_pid}:${candidate_start_time} "
        CORE_PROCESS_COUNT=$((CORE_PROCESS_COUNT + 1))
    done
    return 0
}

core_pid_is_running() {
    actual_start_time=$(core_process_start_time "$1") || return 1
    [ "${actual_start_time}" = "$2" ]
}

is_core_running() {
    core_process_records || return 2
    [ "${CORE_PROCESS_COUNT}" -gt 0 ]
}

write_core_pid() {
    process_record="$1"
    process_pid=${process_record%%:*}
    process_start_time=${process_record#*:}
    temporary_pid_file="${CORE_PID_FILE}.tmp.$$"
    printf '%s\n%s\n' "${process_pid}" "${process_start_time}" > "${temporary_pid_file}" || { rm -f "${temporary_pid_file}"; return 1; }
    mv "${temporary_pid_file}" "${CORE_PID_FILE}"
}

read_registered_core_pid() {
    [ -f "${CORE_PID_FILE}" ] || return 1
    {
        IFS= read -r registered_core_pid || return 1
        IFS= read -r registered_core_start_time || return 1
    } < "${CORE_PID_FILE}"
    core_pid_is_running "${registered_core_pid}" "${registered_core_start_time}"
}

validate_core_config() {
    if [ -f "${COMMAND_ARGS}" ]; then
        if ! grep -q '[^[:space:]]' "${COMMAND_ARGS}" 2>/dev/null; then
            log_msg "core start failed: command_args is empty"
            update_module_description "启动参数文件为空"
            return 1
        fi
        return 0
    fi
    if [ ! -f "${CONFIG_FILE}" ]; then
        log_msg "core start failed: config.toml is missing"
        update_module_description "缺少配置文件"
        return 1
    fi
    if ! grep -q '[^[:space:]]' "${CONFIG_FILE}" 2>/dev/null; then
        log_msg "core start failed: config.toml is empty"
        update_module_description "配置文件为空"
        return 1
    fi
}

read_configuration_status() {
    if [ ! -f "${CONFIG_FILE}" ]; then config_state="missing";
    elif grep -q '[^[:space:]]' "${CONFIG_FILE}" 2>/dev/null; then config_state="present";
    else config_state="empty"; fi
    if [ -f "${COMMAND_ARGS}" ]; then
        if grep -q '[^[:space:]]' "${COMMAND_ARGS}" 2>/dev/null; then command_args_state="present";
        else command_args_state="empty"; fi
    else command_args_state="missing"; fi
}

configuration_status_json() {
    read_configuration_status
    printf '{"config_state":"%s","command_args_state":"%s"}\n' "${config_state}" "${command_args_state}"
}

kill_core() {
    core_process_records || return 1
    [ "${CORE_PROCESS_COUNT}" -gt 0 ] || { rm -f "${CORE_PID_FILE}" 2>/dev/null; return 0; }
    for process_record in ${CORE_PROCESS_RECORDS}; do
        process_pid=${process_record%%:*}
        process_start_time=${process_record#*:}
        core_pid_is_running "${process_pid}" "${process_start_time}" && kill "${process_pid}" 2>/dev/null || true
    done
    wait_count=0
    while [ "${wait_count}" -lt 25 ]; do
        core_process_records || return 1
        [ "${CORE_PROCESS_COUNT}" -gt 0 ] || break
        sleep 0.2
        wait_count=$((wait_count + 1))
    done
    core_process_records || return 1
    for process_record in ${CORE_PROCESS_RECORDS}; do
        process_pid=${process_record%%:*}
        process_start_time=${process_record#*:}
        core_pid_is_running "${process_pid}" "${process_start_time}" && kill -9 "${process_pid}" 2>/dev/null || true
    done
    wait_count=0
    while [ "${wait_count}" -lt 10 ]; do
        core_process_records || return 1
        [ "${CORE_PROCESS_COUNT}" -gt 0 ] || break
        sleep 0.2
        wait_count=$((wait_count + 1))
    done
    core_process_records || return 1
    if [ "${CORE_PROCESS_COUNT}" -gt 0 ]; then
        log_msg "failed to stop easytier-core pid ${process_pid}"
        return 1
    fi
    rm -f "${CORE_PID_FILE}" 2>/dev/null
}

core_mode() {
    if [ -f "${COMMAND_ARGS}" ]; then
        echo "启动参数模式"
    else
        echo "配置文件模式"
    fi
}

start_core_once() {
    if [ -f "${CORE_DISABLE_FILE}" ]; then
        log_msg "core start skipped: disabled"
        return 2
    fi
    validate_core_config || return 1
    core_process_records || { log_msg "core process discovery failed"; return 1; }
    if [ "${CORE_PROCESS_COUNT}" -gt 1 ]; then
        log_msg "multiple easytier-core processes found: ${CORE_PROCESS_RECORDS}"
        update_module_description "检测到多个主程序，请先执行停止或重启"
        return 1
    fi
    if [ "${CORE_PROCESS_COUNT}" -eq 1 ]; then
        write_core_pid "${CORE_PROCESS_RECORDS%% *}" || { log_msg "failed to register running easytier-core"; return 1; }
        log_msg "core already running"
        return 0
    fi
    if [ ! -x "${EASYTIER_CORE}" ]; then
        log_msg "core binary missing or not executable: ${EASYTIER_CORE}"
        update_module_description "主程序缺少二进制文件"
        return 1
    fi
    ensure_tun

    device_hostname=$(get_device_hostname)
    if [ -f "${COMMAND_ARGS}" ]; then
        # command_args mode intentionally uses shell word splitting, matching the upstream module behavior.
        cmd_content=$(tr '\r\n' ' ' < "${COMMAND_ARGS}")
        if echo "${cmd_content}" | grep -q -- "--hostname"; then
            final_args="${cmd_content}"
        else
            final_args="${cmd_content} --hostname ${device_hostname}"
        fi
        log_msg "starting easytier-core with command_args"
        # shellcheck disable=SC2086
        TZ=Asia/Shanghai "${EASYTIER_CORE}" ${final_args} </dev/null > "${LOG_FILE}" 2>&1 &
    else
        log_msg "starting easytier-core with config.toml"
        if grep -q "^[[:space:]]*hostname[[:space:]]*=" "${CONFIG_FILE}" 2>/dev/null; then
            TZ=Asia/Shanghai "${EASYTIER_CORE}" -c "${CONFIG_FILE}" </dev/null > "${LOG_FILE}" 2>&1 &
        else
            TZ=Asia/Shanghai "${EASYTIER_CORE}" -c "${CONFIG_FILE}" --hostname "${device_hostname}" </dev/null > "${LOG_FILE}" 2>&1 &
        fi
    fi
    launched_pid=$!
    launched_start_time=""
    wait_count=0
    while [ "${wait_count}" -lt 20 ]; do
        launched_start_time=$(core_process_start_time "${launched_pid}") && break
        sleep 0.2
        wait_count=$((wait_count + 1))
    done
    if [ -n "${launched_start_time}" ] && core_pid_is_running "${launched_pid}" "${launched_start_time}"; then
        write_core_pid "${launched_pid}:${launched_start_time}" || { log_msg "failed to register launched easytier-core"; return 1; }
        if ! ip rule show 2>/dev/null | grep -qE '^[0-9]+:[[:space:]]+from all lookup main$'; then
            ip rule add from all lookup main >/dev/null 2>&1 || true
        fi
        update_module_description "主程序正在运行（$(core_mode)）| $(redir_status)"
        return 0
    fi
    update_module_description "主程序启动失败，请检查配置文件或启动参数"
    return 1
}

redir_status() {
    if [ -f "${IP_RULE_ENABLE_FILE}" ]; then
        echo "转发已激活"
    else
        echo "转发已禁用"
    fi
}

module_status_json() {
    if read_registered_core_pid; then
        core_discovery_error=false
        core_running=true
        CORE_PROCESS_COUNT=1
    elif core_process_records; then
        core_discovery_error=false
        [ "${CORE_PROCESS_COUNT}" -gt 0 ] && core_running=true || core_running=false
    else
        core_discovery_error=true
        core_running=false
    fi
    if [ -f "${MODULE_DISABLE_FILE}" ]; then module_enabled=false; else module_enabled=true; fi
    if [ -f "${CORE_DISABLE_FILE}" ]; then core_enabled=false; else core_enabled=true; fi
    if [ -f "${START_ON_BOOT_FILE}" ]; then start_on_boot=true; else start_on_boot=false; fi
    if [ -f "${IP_RULE_ENABLE_FILE}" ]; then ip_rule_enabled=true; else ip_rule_enabled=false; fi
    read_configuration_status
    module_version=""
    if [ -r "${MODULE_PROP}" ]; then
        while IFS= read -r module_property_line; do
            case "${module_property_line}" in
                version=*) module_version=${module_property_line#version=}; break ;;
            esac
        done < "${MODULE_PROP}"
    fi
    printf '{'
    printf '"module_enabled":%s,' "${module_enabled}"
    printf '"core_running":%s,' "${core_running}"
    printf '"core_count":%s,' "${CORE_PROCESS_COUNT}"
    printf '"core_discovery_error":%s,' "${core_discovery_error}"
    printf '"core_enabled":%s,' "${core_enabled}"
    printf '"start_on_boot":%s,' "${start_on_boot}"
    printf '"ip_rule_enabled":%s,' "${ip_rule_enabled}"
    printf '"config_state":"%s",' "${config_state}"
    printf '"command_args_state":"%s",' "${command_args_state}"
    printf '"config_path":"%s",' "${CONFIG_FILE}"
    printf '"command_args_path":"%s",' "${COMMAND_ARGS}"
    printf '"module_version":"%s"' "$(printf '%s' "${module_version}" | json_escape)"
    printf '}\n'
}

current_process_start_time() {
    current_stat_line=""
    IFS= read -r current_stat_line < "/proc/$$/stat" || { echo unknown; return 0; }
    current_stat_fields=${current_stat_line##*) }
    current_field_index=0
    for current_stat_field in ${current_stat_fields}; do
        current_field_index=$((current_field_index + 1))
        if [ "${current_field_index}" -eq 20 ]; then
            echo "${current_stat_field}"
            return 0
        fi
    done
    echo unknown
}

control_lock_owner_is_alive() {
    owner_directory="$1"
    owner_pid=$(sed -n '1p' "${owner_directory}/pid" 2>/dev/null)
    owner_start_time=$(sed -n '1p' "${owner_directory}/start" 2>/dev/null)
    case "${owner_pid}" in ''|*[!0-9]*) return 1 ;; esac
    kill -0 "${owner_pid}" 2>/dev/null || return 1
    [ "${owner_start_time}" = "unknown" ] && return 0
    current_owner_start_time=$(process_start_time_for_pid "${owner_pid}") || return 1
    [ "${current_owner_start_time}" = "${owner_start_time}" ]
}

process_start_time_for_pid() {
    owner_stat_line=""
    IFS= read -r owner_stat_line < "/proc/$1/stat" || return 1
    owner_stat_fields=${owner_stat_line##*) }
    set -- ${owner_stat_fields}
    [ "$#" -ge 20 ] || return 1
    shift 19
    echo "$1"
}

recover_control_lock() {
    observed_owner_directory=""
    if [ -L "${CONTROL_LOCK_DIR}" ]; then
        observed_owner_directory=$(readlink "${CONTROL_LOCK_DIR}" 2>/dev/null)
        [ -n "${observed_owner_directory}" ] || return 1
        mkdir "${observed_owner_directory}/reaper" 2>/dev/null || return 1
        if [ "$(readlink "${CONTROL_LOCK_DIR}" 2>/dev/null)" = "${observed_owner_directory}" ] && \
            ! control_lock_owner_is_alive "${observed_owner_directory}"; then
            rm -f "${CONTROL_LOCK_DIR}"
            rm -rf "${observed_owner_directory}"
            return 0
        fi
        rmdir "${observed_owner_directory}/reaper" 2>/dev/null || true
        return 1
    fi

    [ -d "${CONTROL_LOCK_DIR}" ] || return 1
    mkdir "${CONTROL_LOCK_DIR}/reaper" 2>/dev/null || return 1
    lock_owner=$(cat "${CONTROL_LOCK_DIR}/pid" 2>/dev/null)
    lock_start=$(cat "${CONTROL_LOCK_DIR}/start" 2>/dev/null)
    if [ -n "${lock_owner}" ]; then
        lock_owner_is_stale=0
        if ! kill -0 "${lock_owner}" 2>/dev/null; then
            lock_owner_is_stale=1
        elif [ -n "${lock_start}" ] && [ "${lock_start}" != "unknown" ]; then
            current_lock_start=$(process_start_time_for_pid "${lock_owner}")
            [ "${current_lock_start}" = "${lock_start}" ] || lock_owner_is_stale=1
        fi
        if [ "${lock_owner_is_stale}" = 1 ]; then
            rm -rf "${CONTROL_LOCK_DIR}"
            return 0
        fi
    fi
    if [ -z "${lock_owner}" ] && [ "${wait_count}" -ge 10 ]; then
        rm -rf "${CONTROL_LOCK_DIR}"
        return 0
    fi
    rmdir "${CONTROL_LOCK_DIR}/reaper" 2>/dev/null || true
    return 1
}

control_lock_acquire() {
    maximum_wait_count=${1:-50}
    mkdir -p "${RUN_DIR}" 2>/dev/null || return 1
    wait_count=0
    while [ "${wait_count}" -lt "${maximum_wait_count}" ]; do
        if mkdir "${CONTROL_LOCK_DIR}" 2>/dev/null; then
            CONTROL_LOCK_OWNER_DIR="$$"
            CONTROL_LOCK_OWNER_START=$(current_process_start_time)
            printf '%s\n' "${CONTROL_LOCK_OWNER_DIR}" > "${CONTROL_LOCK_DIR}/pid" || { rm -rf "${CONTROL_LOCK_DIR}"; return 1; }
            printf '%s\n' "${CONTROL_LOCK_OWNER_START}" > "${CONTROL_LOCK_DIR}/start" || { rm -rf "${CONTROL_LOCK_DIR}"; return 1; }
            return 0
        fi
        recover_control_lock && continue
        wait_count=$((wait_count + 1))
        sleep 0.1
    done
    return 1
}

control_lock_release() {
    [ -n "${CONTROL_LOCK_OWNER_DIR}" ] || return 0
    lock_owner=$(cat "${CONTROL_LOCK_DIR}/pid" 2>/dev/null)
    lock_start=$(cat "${CONTROL_LOCK_DIR}/start" 2>/dev/null)
    if [ "${lock_owner}" = "${CONTROL_LOCK_OWNER_DIR}" ] && [ "${lock_start}" = "${CONTROL_LOCK_OWNER_START}" ]; then
        rm -f "${CONTROL_LOCK_DIR}/pid" "${CONTROL_LOCK_DIR}/start"
        rmdir "${CONTROL_LOCK_DIR}" 2>/dev/null || true
    fi
    CONTROL_LOCK_OWNER_DIR=""
    CONTROL_LOCK_OWNER_START=""
}
